# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('body', django_mysql.models.SizedTextField(size_class=4, verbose_name=3)),
                ('publisher', models.CharField(max_length=15)),
                ('tags', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
